apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql_service.name }}
  namespace: {{ .Values.mysql_namespace }}
spec:
  selector:
    app: {{ .Values.mysql_service.app }}
  ports:
    - protocol:  {{ .Values.ports2.protocol }}
      port: {{ .Values.ports2.port }}
      targetPort: {{ .Values.ports2.targetPort }}