apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.wp_deployment.name }}
  namespace: {{ .Values.wp_namespace }}
spec:
  selector:
    app: {{ .Values.wp_deployment.appname }}
  ports:
    - protocol: {{.Values.ports.protocol }}
      port: {{ .Values.ports.port }}
      targetPort: {{ .Values.ports.targetPort }}